<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
## <font color='blue'>Automação de Processos e Engenharia de Dados com Python, Excel e IA</font>
## <font color='blue'>Projeto 1</font>
## <font color='blue'>Engenharia de Dados de E-commerce com Python e Excel</font>

## Pacotes Python Usados no Projeto

In [1]:
# Instala o pacote watermark
!pip install -q -U watermark

In [2]:
# Pacote para extração de dados do Excel. O pandas requer este pacote instalado ao manipular dados do Excel.
# Procedimento de instalação no arquivo LEIAME.txt
#!pip install -q xlrd

In [3]:
# Imports
import xlrd
import numpy as np
import pandas as pd

In [4]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

## Carregando a Planilha Excel Como DataFrame do Pandas

In [5]:
# Carrega os dados
df_dsa = pd.read_excel('dataset.xls')

In [6]:
type(df_dsa)

pandas.core.frame.DataFrame

In [7]:
# Shape
df_dsa.shape

(9994, 21)

In [8]:
# Amostra
df_dsa.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## Análise Exploratória

In [9]:
# Colunas
df_dsa.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [10]:
df_dsa.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [11]:
# Resumo estatístico 
df_dsa.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [12]:
# Total de produtos únicos
len(pd.unique(df_dsa['Product ID']))

1862

In [13]:
# Produtos únicos
np.unique(df_dsa['Product ID'])

array(['FUR-BO-10000112', 'FUR-BO-10000330', 'FUR-BO-10000362', ...,
       'TEC-PH-10004924', 'TEC-PH-10004959', 'TEC-PH-10004977'],
      shape=(1862,), dtype=object)

In [14]:
# Total de registros únicos por coluna
for col in df_dsa.columns:
    print (col,'>>>>',len(np.unique(df_dsa[col])))

Row ID >>>> 9994
Order ID >>>> 5009
Order Date >>>> 1237
Ship Date >>>> 1334
Ship Mode >>>> 4
Customer ID >>>> 793
Customer Name >>>> 793
Segment >>>> 3
Country >>>> 1
City >>>> 531
State >>>> 49
Postal Code >>>> 631
Region >>>> 4
Product ID >>>> 1862
Category >>>> 3
Sub-Category >>>> 17
Product Name >>>> 1850
Sales >>>> 6144
Quantity >>>> 14
Discount >>>> 12
Profit >>>> 7545

## Pipeline 1 - Estatísticas de Vendas com Pivot Table

Objetivo: Criar uma tabela com a média e desvio padrão de vendas e lucro por subcategoria. A tabela deve conter para cada registro a diferença entre a média e o desvio padrão.

Média é um valor que tenta resumir um conjunto de dados representando o "centro" desses dados. É calculada somando todos os valores do conjunto e dividindo o total pelo número de valores. A média dá uma boa ideia do que é típico ou comum para aquele conjunto de dados.

Desvio padrão é uma medida que indica a quantidade de variação ou dispersão dos dados em relação à média. Um desvio padrão baixo significa que os dados estão agrupados muito próximos da média, indicando pouca variação. Um desvio padrão alto indica que os dados estão mais espalhados, mostrando uma maior variação em relação à média.

In [15]:
# Média de vendas (Sales) e média de lucro (Profit)
df_dsa_media_info = pd.pivot_table(df_dsa,
                                   index = 'Sub-Category',
                                   values = ['Sales', 'Profit'], aggfunc = 'mean').reset_index()

In [16]:
# Ajusta os nomes das colunas
df_dsa_media_info.columns = ['Sub-Category', 'MeanProfit', 'MeanSales']

In [17]:
# Visualiza amostra dos dados
df_dsa_media_info.head()

  Sub-Category  MeanProfit   MeanSales
0  Accessories   54.111788  215.974604
1   Appliances   38.922758  230.755710
2          Art    8.200737   34.068834
3      Binders   19.843574  133.560560
4    Bookcases  -15.230509  503.859633

In [18]:
# Desvio padrão de vendas (Sales) e desvio padrão de lucro (Profit)
df_dsa_desvio_info = pd.pivot_table(df_dsa, 
                                    index = 'Sub-Category',
                                    values = ['Sales', 'Profit'], aggfunc = 'std').reset_index()

In [19]:
# Ajusta os nomes das colunas
df_dsa_desvio_info.columns = ['Sub-Category', 'STDProfit', 'STDSales']

In [20]:
# Visualiza amostra dos dados
df_dsa_desvio_info.head()

  Sub-Category   STDProfit    STDSales
0  Accessories  106.155455  334.965015
1   Appliances  148.319146  388.949643
2          Art   13.384264   60.122465
3      Binders  306.196773  563.251188
4    Bookcases  182.034224  638.748523

In [21]:
# Merde das tabelas
df_pipe_1 = pd.merge(df_dsa_media_info, df_dsa_desvio_info, on = 'Sub-Category', how = 'left')

In [22]:
df_pipe_1.head()

  Sub-Category  MeanProfit   MeanSales   STDProfit    STDSales
0  Accessories   54.111788  215.974604  106.155455  334.965015
1   Appliances   38.922758  230.755710  148.319146  388.949643
2          Art    8.200737   34.068834   13.384264   60.122465
3      Binders   19.843574  133.560560  306.196773  563.251188
4    Bookcases  -15.230509  503.859633  182.034224  638.748523

In [23]:
# Calcula a diferença da média de lucro em relação ao desvio
df_pipe_1['diffMean'] = df_pipe_1['MeanProfit'] - df_pipe_1['STDProfit']

In [24]:
# Calcula a diferença da média de vendas em relação ao desvio
df_pipe_1['diffSTD'] = df_pipe_1['MeanSales'] - df_pipe_1['STDSales']

In [25]:
# Ordena a tabela
df_pipe_1.sort_values(by = ['diffMean'], ascending = False)

,Sub-Category,MeanProfit,MeanSales,STDProfit,STDSales,diffMean,diffSTD
8,Fasteners,4.375660,13.936774,5.055053,12.416593,-0.679393,1.520181
2,Art,8.200737,34.068834,13.384264,60.122465,-5.183527,-26.053631
7,Envelopes,27.418019,64.867724,35.354983,84.351633,-7.936964,-19.483908
12,Paper,24.856620,57.284092,35.225214,78.167639,-10.368594,-20.883547
10,Labels,15.236962,34.303055,34.084127,74.119287,-18.847165,-39.816232
9,Furnishings,13.645918,95.825668,52.753228,147.893640,-39.107310,-52.067972
0,Accessories,54.111788,215.974604,106.155455,334.965015,-52.043667,-118.990411
14,Storage,25.152277,264.590553,81.923600,355.222507,-56.771323,-90.631953
13,Phones,50.073938,371.211534,113.251277,491.457343,-63.177339,-120.245808
5,Chairs,43.095894,532.332420,127.099922,550.148243,-84.004028,-17.815823
1,Appliances,38.922758,230.755710,148.319146,388.949643,-109.396388,-158.193933
15,Supplies,-6.258418,245.650200,105.059628,923.828753,-111.318047,-678.178553
4,Bookcases,-15.230509,503.859633,182.034224,638.748523,-197.264733,-134.888890
16,Tables,-55.565771,648.794771,230.565006,615.774655,-286.130778,33.020116
3,Binders,19.843574,133.560560,306.196773,563.251188,-286.353199,-429.690627
6,Copiers,817.909190,2198.941618,1460.921156,3175.665867,-643.011967,-976.724250
11,Machines,29.432669,1645.553313,1099.070067,2765.102088,-1069.637398,-1119.548775

In [26]:
type(df_pipe_1)

pandas.core.frame.DataFrame

## Pipeline 2 - Resumo de Vendas com Pivot Table

Objetivo: Identificar as subcategorias onde estão os 20 principais clientes que têm vendas maiores do que as outras subcategorias na mesma região.

In [27]:
# Colunas
df_dsa.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [28]:
# Tabela pivot para extrair os 20 clientes com maior volume de vendas
df_cliente = pd.pivot_table(df_dsa,
                            index = ['Customer ID'],
                            values = ['Sales'], 
                            aggfunc = 'sum').reset_index().sort_values(by = 'Sales',
                                                                       ascending = False).head(20)['Customer ID'].values

In [29]:
df_cliente

array(['SM-20320', 'TC-20980', 'RB-19360', 'TA-21385', 'AB-10105',
       'KL-16645', 'SC-20095', 'HL-15040', 'SE-20110', 'CC-12370',
       'TS-21370', 'GT-14710', 'BM-11140', 'SV-20365', 'CJ-12010',
       'CL-12565', 'ME-17320', 'KF-16285', 'BS-11365', 'EH-13765'],
      dtype=object)

In [30]:
# Valores únicos de Região
pd.unique(df_dsa['Region'])

array(['South', 'West', 'Central', 'East'], dtype=object)

In [31]:
# Filtra os dados dos clientes com maior volume de vendas
df_dados_filtrados = df_dsa[(df_dsa['Customer ID'].isin(df_cliente))]

In [32]:
# Pivot table
df_pipe_2 = pd.pivot_table(df_dados_filtrados, 
                           index = 'Sub-Category',
                           columns = ['Region'],
                           values = ['Sales'])

In [33]:
df_pipe_2.head()

                    Sales
Region            Central        East       South        West
Sub-Category
Accessories     36.027000  100.938889  498.000000  125.175667
Appliances     122.191000  222.697200         NaN  207.082500
Art             26.999111   49.739091   11.260750   39.927200
Binders       1486.914267  274.165625  427.466167   41.815200
Bookcases     1023.332000  995.506800  145.740000  413.488500

In [34]:
# Colunas
df_pipe_2.columns

MultiIndex([('Sales', 'Central'),
            ('Sales',    'East'),
            ('Sales',   'South'),
            ('Sales',    'West')],
           names=[None, 'Region'])

In [35]:
# Join
df_pipe_2.columns = [''.join(i) for i in df_pipe_2.columns]

In [36]:
# Ordenação
df_pipe_2.sort_values(by = 'SalesCentral')

              SalesCentral    SalesEast    SalesSouth    SalesWest
Sub-Category
Labels           11.960000    44.400000     15.750000    21.170000
Fasteners        15.692000     4.360000     25.028000     7.280000
Art              26.999111    49.739091     11.260750    39.927200
Envelopes        35.093333    58.206000     23.340000    92.630000
Accessories      36.027000   100.938889    498.000000   125.175667
Paper            39.236286    41.751500     17.522800    88.103125
Appliances      122.191000   222.697200           NaN   207.082500
Furnishings     129.247500    88.888182    156.064286   102.971250
Storage         189.164500   447.360000    193.770000   199.485400
Supplies        197.585000    18.153000      3.328000  2983.951200
Tables          481.096250   199.836000    693.101000   647.938500
Phones          515.872444   452.395571    417.548000   948.608800
Chairs         1016.881667   787.300846   1667.744000   576.258667
Bookcases      1023.332000   995.506800    145.740000   413.488500
Binders        1486.914267   274.165625    427.466167    41.815200
Machines       4223.931000  4919.940000  10736.576667  1553.480000
Copiers       10149.955000  7674.971000           NaN  8399.960000

## Pipeline 3 - Resumo de Vendas com Pivot Table e Agregação

Objetivo: Total de vendas por subcategoria de produto somente da região Central, dos 20 clientes com maior volume de vendas.

In [37]:
# Valores únicos de Região
pd.unique(df_dsa['Region'])

array(['South', 'West', 'Central', 'East'], dtype=object)

In [38]:
# Pivot table
df_vendas_regiao = df_dsa.pivot_table(index = ['Region','Customer ID'],
                                      values = 'Sales',
                                      aggfunc = 'sum').reset_index()

In [39]:
# Vendas da região Central
df_vendas_central = df_vendas_regiao[df_vendas_regiao['Region']=='Central'].sort_values(by = 'Sales', 
                                                                                        ascending = False).head(20)['Customer ID'].values

In [40]:
# Dados filtrados
dados_filtrados = df_dsa[(df_dsa['Customer ID'].isin(df_vendas_central)) & (df_dsa['Region'] == 'Central') ]

In [41]:
# Pivot table
df_pipe_3 = dados_filtrados.pivot_table(index = 'Customer ID', 
                                        columns = ['Sub-Category'],
                                        values = 'Sales',
                                        aggfunc = 'sum')

In [42]:
# Soma e ordenação
df_pipe_3.sum(axis = 0).sort_values(ascending = False)

Sub-Category
Binders        33153.2340
Copiers        25349.8300
Machines       15035.7810
Chairs         13541.4140
Phones         10379.3520
Supplies        8116.0820
Appliances      5839.7030
Accessories     4115.5540
Storage         3680.5500
Bookcases       1994.7788
Paper           1770.5920
Furnishings     1069.8600
Labels           590.4240
Tables           435.1650
Envelopes        422.1280
Art              352.6500
Fasteners          7.0240
dtype: float64

## Pipeline 4 - Group By Para Relatório de Vendas e Percentual de Lucro

Objetivo: Criar tabela contendo região, cliente, total de vendas, total de lucro e percentual de lucro em relação às vendas.

In [43]:
# Group by com cálculo de soma
df_pipe_4 = df_dsa.groupby(['Region','Customer ID']).agg({'Sales':'sum','Profit':'sum'}).reset_index()

In [44]:
df_pipe_4.head()

    Region Customer ID     Sales    Profit
0  Central    AA-10315  4780.552 -650.5971
1  Central    AA-10375   178.370   62.0658
2  Central    AA-10480  1747.500  420.4986
3  Central    AA-10645  1971.460  439.3138
4  Central    AB-10015   576.564  114.3432

In [45]:
# Calcula a taxa de lucro percentual
df_pipe_4['profitRatio'] = df_pipe_4['Profit'] / df_pipe_4['Sales']

In [46]:
# Ordenação
df_pipe_4 = df_pipe_4.sort_values(['Region','profitRatio'], ascending = False)

In [47]:
# Reset do índice
df_pipe_4 = df_pipe_4.reset_index()

In [48]:
# Visualiza
df_pipe_4

      index   Region Customer ID    Sales    Profit  profitRatio
0      2206     West    LB-16735   21.480   10.7400     0.500000
1      2367     West    RD-19810  146.820   73.4100     0.500000
2      2422     West    SM-20320    9.960    4.8804     0.490000
3      1939     West    CG-12040   11.760    5.7624     0.490000
4      2468     West    TP-21415   12.960    6.3504     0.490000
...     ...      ...         ...      ...       ...          ...
2496    340  Central    KN-16450   48.632 -121.5800    -2.500000
2497    550  Central    SJ-20500   97.264 -243.1600    -2.500000
2498    561  Central    SP-20920   23.992  -62.3792    -2.600000
2499    390  Central    MG-17695  145.504 -392.8595    -2.699991
2500    195  Central    Dl-13600    1.624   -4.4660    -2.750000

[2501 rows x 6 columns]

In [49]:
# 5 maiores valores de vendas (exemplo)
df_pipe_4.nlargest(5,'Sales')

      index   Region Customer ID      Sales     Profit  profitRatio
1127   1754    South    SM-20320  23669.196 -1787.0435    -0.075501
1885    588  Central    TC-20980  18437.138  8745.0635     0.474318
18     2354     West    RB-19360  14345.276  6807.0879     0.474518
1334   1250     East    TA-21385  13723.498  4599.2073     0.335134
1909      6  Central    AB-10105  12181.594  5362.6135     0.440223

In [50]:
# Agrupando pela média dos 20 maiores valores (exemplo)
df_pipe_4.groupby(['Region']).agg({'profitRatio':{lambda x: x.nlargest(20).mean()}})

        profitRatio
           <lambda>
Region
Central    0.479799
East       0.484697
South      0.481304
West       0.482885

In [51]:
# Filtrando por uma das regiões (exemplo)
df_pipe_4[df_pipe_4['Region']=='West'].head()['profitRatio'].mean()

np.float64(0.49399999999999994)

## Pipeline 5 - Stacking de Dataframe

Objetivo: Os dados serão reorganizados empilhados verticalmente uns sobre os outros.

In [52]:
df_pipe_4.head()

   index Region Customer ID   Sales   Profit  profitRatio
0   2206   West    LB-16735   21.48  10.7400         0.50
1   2367   West    RD-19810  146.82  73.4100         0.50
2   2422   West    SM-20320    9.96   4.8804         0.49
3   1939   West    CG-12040   11.76   5.7624         0.49
4   2468   West    TP-21415   12.96   6.3504         0.49

In [53]:
# Stack
df_pipe_5 = df_pipe_4.stack()

In [54]:
df_pipe_5.head(20)

0  index              2206
   Region             West
   Customer ID    LB-16735
   Sales             21.48
   Profit            10.74
   profitRatio         0.5
1  index              2367
   Region             West
   Customer ID    RD-19810
   Sales            146.82
   Profit            73.41
   profitRatio         0.5
2  index              2422
   Region             West
   Customer ID    SM-20320
   Sales              9.96
   Profit           4.8804
   profitRatio        0.49
3  index              1939
   Region             West
dtype: object

In [55]:
# Unstack se necessário
df_pipe_5.unstack()

     index   Region Customer ID    Sales    Profit profitRatio
0     2206     West    LB-16735    21.48     10.74         0.5
1     2367     West    RD-19810   146.82     73.41         0.5
2     2422     West    SM-20320     9.96    4.8804        0.49
3     1939     West    CG-12040    11.76    5.7624        0.49
4     2468     West    TP-21415    12.96    6.3504        0.49
...    ...      ...         ...      ...       ...         ...
2496   340  Central    KN-16450   48.632   -121.58        -2.5
2497   550  Central    SJ-20500   97.264   -243.16        -2.5
2498   561  Central    SP-20920   23.992  -62.3792        -2.6
2499   390  Central    MG-17695  145.504 -392.8595   -2.699991
2500   195  Central    Dl-13600    1.624    -4.466       -2.75

[2501 rows x 6 columns]

## Salvando Todos os Dataframes na Mesma Planilha Excel

In [56]:
with pd.ExcelWriter('df_dsa_report.xlsx', engine='openpyxl') as writer:
    df_pipe_1.to_excel(writer, sheet_name='Report1', index=False)
    df_pipe_2.to_excel(writer, sheet_name='Report2', index=False)
    df_pipe_3.to_excel(writer, sheet_name='Report3', index=False)
    df_pipe_4.to_excel(writer, sheet_name='Report4', index=False)
    df_pipe_5.to_excel(writer, sheet_name='Report5', index=False)

In [57]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

In [58]:
#%watermark -v -m

In [59]:
#%watermark --iversions

# Fim