<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
## <font color='blue'>Automação de Processos e Engenharia de Dados com Python, Excel e IA</font>
## <font color='blue'>Lab 2</font>
## <font color='blue'>Técnicas de Slicing, Dicing, Mapeamento e Merge Para Processamento de Dados</font>

## Pacotes Python Usados no Projeto

In [1]:
# Instala o pacote watermark
%pip install -q -U watermark

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# Imports
import datetime
import pandas as pd
import numpy as np

In [3]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

## Seleção e Slicing com Filtro Por String

In [4]:
# Carrega o dataset
df_dsa1 = pd.read_csv('dataset1.csv')

In [5]:
type(df_dsa1)

pandas.core.frame.DataFrame

In [6]:
# Visualiza amostra dos dados
df_dsa1.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [7]:
df_dsa1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

Em Python, as strings são um tipo de dado que representam sequências de caracteres. São objetos do tipo str e são utilizadas para armazenar e manipular texto.

Por outro lado, o termo "object" em Python refere-se a qualquer instância de uma classe. Em Python, tudo é um objeto, incluindo strings, listas, dicionários, funções e até mesmo tipos de dados mais simples, como inteiros e floats. Isso significa que todos esses tipos de dados possuem métodos e atributos associados a eles, que podem ser acessados e manipulados.

Portanto, a principal diferença é que str é um tipo específico de objeto usado para representar texto, enquanto "object" é um termo genérico que se refere a qualquer instância de uma classe em Python.

In [8]:
# Comparação com string
df_dsa1['Android Ver'].str[0] == '2'

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838     True
10839    False
10840    False
Name: Android Ver, Length: 10841, dtype: bool

Esta expressão acima é usada para verificar se o primeiro caractere de cada elemento na coluna 'Android Ver' é igual a '2'. O .str permite acessar métodos de string vetorizados, o que significa que você pode aplicar operações de string elemento a elemento em toda a coluna. O resultado desta expressão é uma série booleana com o mesmo tamanho que a coluna 'Android Ver', onde cada elemento indica se a condição é verdadeira ou falsa para o respectivo elemento na coluna.

In [9]:
# Comparação com string
df_dsa1['Android Ver'][0] == '2'

False

Esta expressão acima é usada para acessar o primeiro elemento da coluna 'Android Ver' e depois verificar se o primeiro caractere desse elemento específico é igual a '2'. Em outras palavras, esta expressão não é aplicada a toda a coluna, mas apenas ao primeiro elemento. O resultado é um único valor booleano, indicando se a condição é verdadeira ou falsa para o primeiro elemento da coluna.

In [10]:
# Comparação com string
df_dsa1['Android Ver'] == '2'

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Android Ver, Length: 10841, dtype: bool

A expressão acima é usada para comparar todos os elementos da coluna 'Android Ver' com a string '2'. O resultado é uma série booleana com o mesmo tamanho que a coluna 'Android Ver', onde cada elemento indica se a condição é verdadeira ou falsa para o respectivo elemento na coluna.

In [11]:
# Slicing com filtro por string
df_dsa1[df_dsa1['Android Ver'].str[0] == '2']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
14,3D Color Pixel by Number - Sandbox Art Coloring,ART_AND_DESIGN,4.4,1518,37M,"100,000+",Free,0,Everyone,Art & Design,"August 3, 2018",1.2.3,2.3 and up
17,350 Diy Room Decor Ideas,ART_AND_DESIGN,4.5,27,17M,"10,000+",Free,0,Everyone,Art & Design,"November 7, 2017",1.0,2.3 and up
28,Pencil Sketch Drawing,ART_AND_DESIGN,3.9,136,4.6M,"10,000+",Free,0,Everyone,Art & Design,"July 12, 2018",6.0,2.3 and up
29,Easy Realistic Drawing Tutorial,ART_AND_DESIGN,4.1,223,4.2M,"100,000+",Free,0,Everyone,Art & Design,"August 22, 2017",1.0,2.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10808,lesparticuliers.fr,LIFESTYLE,NaN,96,1.0M,"50,000+",Free,0,Everyone,Lifestyle,"November 25, 2014",1.5,2.3 and up
10818,Gold Quote - Gold.fr,FINANCE,NaN,96,1.5M,"10,000+",Free,0,Everyone,Finance,"May 19, 2016",2.3,2.2 and up
10832,FR Tides,WEATHER,3.8,1195,582k,"100,000+",Free,0,Everyone,Weather,"February 16, 2014",6.0,2.1 and up
10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,44,619k,"1,000+",Free,0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up

In [12]:
# Slicing com filtro por string
# df_dsa1[df_dsa1['Android Ver'][0] == '2']

In [13]:
# Slicing com filtro por string
df_dsa1[df_dsa1['Android Ver'] == '2']

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [14]:
df_dsa1['Type'].value_counts()

Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64

In [15]:
# Comparação com string
df_dsa1['Type'] == 'Paid'

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Type, Length: 10841, dtype: bool

In [16]:
# Slicing com filtro por string
df_dsa1[df_dsa1['Type'] == 'Paid']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
234,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,$4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,$4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
290,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,$4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
291,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,$4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
427,Puffin Browser Pro,COMMUNICATION,4.0,18247,Varies with device,"100,000+",Paid,$3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10735,FP VoiceBot,FAMILY,NaN,17,157k,100+,Paid,$0.99,Mature 17+,Entertainment,"November 25, 2015",1.2,2.1 and up
10760,Fast Tract Diet,HEALTH_AND_FITNESS,4.4,35,2.4M,"1,000+",Paid,$7.99,Everyone,Health & Fitness,"August 8, 2018",1.9.3,4.2 and up
10782,Trine 2: Complete Story,GAME,3.8,252,11M,"10,000+",Paid,$16.99,Teen,Action,"February 27, 2015",2.22,5.0 and up
10785,"sugar, sugar",FAMILY,4.2,1405,9.5M,"10,000+",Paid,$1.20,Everyone,Puzzle,"June 5, 2018",2.7,2.3 and up
10798,Word Search Tab 1 FR,FAMILY,NaN,0,1020k,50+,Paid,$1.04,Everyone,Puzzle,"February 6, 2012",1.1,3.0 and up

In [17]:
# Slicing com filtro por string e filtro por coluna
price = df_dsa1[df_dsa1['Type'] == 'Paid']['Price']

In [18]:
price

234       $4.99
235       $4.99
290       $4.99
291       $4.99
427       $3.99
          ...
10735     $0.99
10760     $7.99
10782    $16.99
10785     $1.20
10798     $1.04
Name: Price, Length: 800, dtype: object

In [19]:
# Cria uma lista
price_lst = []

In [20]:
# Loop para preencher a lista com os valores numéricos removendo o símbolo $ 
for each_row in price:
    price_lst.append(pd.to_numeric(each_row.split('$')[1]))

In [21]:
# Visualiza os primeiros 20 registros da lista
price_lst[:20]

[np.float64(4.99),
 np.float64(4.99),
 np.float64(4.99),
 np.float64(4.99),
 np.float64(3.99),
 np.float64(3.99),
 np.float64(6.99),
 np.float64(1.49),
 np.float64(2.99),
 np.float64(3.99),
 np.float64(7.99),
 np.float64(3.99),
 np.float64(3.99),
 np.float64(5.99),
 np.float64(3.99),
 np.float64(3.99),
 np.float64(4.99),
 np.float64(2.99),
 np.float64(3.49),
 np.float64(4.99)]

In [22]:
# Retorna uma posição do dataframe
df_dsa1['Price'][235]

'$4.99'

In [23]:
# Retorna uma posição do dataframe fazendo o split pelo $
df_dsa1['Price'][235].split('$')

['', '4.99']

In [24]:
# Faz o split e retorna a coluna de índice 1
df_dsa1['Price'][235].split('$')[1]

'4.99'

In [25]:
# Observe o tipo retornado
type(df_dsa1['Price'][235].split('$')[1])

str

In [26]:
# Isso não pode ser feito. Leia a mensagem de erro!
# df_dsa1['Price'][235].split('$')[1] + 1

In [27]:
# Concatena strings
df_dsa1['Price'][235].split('$')[1] + '1'

'4.991'

In [28]:
# Converte para float
float(df_dsa1['Price'][235].split('$')[1])

4.99

In [29]:
# Operação de soma
float(df_dsa1['Price'][235].split('$')[1]) + 1

5.99

## Seleção e Slicing Por Labels

In [30]:
# Carregando os dados
df_dsa2 = pd.read_csv('dataset2.csv')

In [31]:
# 5 primeiras linhas
df_dsa2.head()

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
0,47,100,27,81,57,37,26,0,0,23,56.0,53,100,90,40,98,8
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2
2,0,57,31,68,72,90,100,100,76,75,50.0,51,28,25,16,0,1
3,0,100,7,92,5,68,19,45,86,34,100.0,45,74,23,67,0,4
4,0,67,49,83,100,100,81,80,60,60,40.0,40,33,20,47,0,1

In [32]:
# 5 últimas linhas
df_dsa2.tail()

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
10987,36,100,24,70,0,38,49,33,95,47,87.0,55,96,21,100,0,4
10988,16,75,41,100,52,64,32,27,0,0,21.0,9,62,2,100,14,2
10989,56,100,27,79,0,39,12,0,66,15,100.0,51,93,93,38,93,0
10990,19,100,0,61,3,23,48,0,97,27,100.0,66,62,97,10,81,0
10991,38,100,37,81,12,55,0,28,52,27,100.0,42,86,26,65,0,4

In [33]:
# Colunas
df_dsa2.columns

Index(['input1', 'input2', 'input3', 'input4', 'input5', 'input6', 'input7',
       'input8', 'input9', 'input10', 'input11', 'input12', 'input13',
       'input14', 'input15', 'input16', 'class'],
      dtype='object')

In [34]:
# Tipos de dados
df_dsa2.dtypes

input1       int64
input2       int64
input3       int64
input4       int64
input5       int64
input6       int64
input7       int64
input8       int64
input9       int64
input10      int64
input11    float64
input12      int64
input13      int64
input14      int64
input15      int64
input16      int64
class        int64
dtype: object

In [35]:
# Índices do dataframe
df_dsa2.index

RangeIndex(start=0, stop=10992, step=1)

In [36]:
df_dsa2.head(2)

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
0,47,100,27,81,57,37,26,0,0,23,56.0,53,100,90,40,98,8
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2

In [37]:
df_dsa2.loc[1]

input1       0.0
input2      89.0
input3      27.0
input4     100.0
input5      42.0
input6      75.0
input7      29.0
input8      45.0
input9      15.0
input10     15.0
input11     37.0
input12      0.0
input13     69.0
input14      2.0
input15    100.0
input16      6.0
class        2.0
Name: 1, dtype: float64

Quando você passa 1 dentro de .loc[], o pandas busca a linha cujo índice é 1. É importante notar que isso se refere ao rótulo do índice e não necessariamente à primeira posição. CUIDADO!

In [38]:
df_dsa2.loc[[1]]

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2

O código df_dsa2.loc[[1]] no pandas serve para acessar uma linha específica de um DataFrame, mantendo a estrutura de DataFrame. Diferentemente de df_dsa2.loc[1] que retorna uma série (uma linha única em formato de lista), usar df_dsa2.loc[[1]] com colchetes duplos retorna um DataFrame contendo apenas a linha cujo índice é 1. Isso é útil quando você quer manter o formato de tabela, mesmo acessando apenas uma linha.

In [39]:
df_dsa2.loc[:3]

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
0,47,100,27,81,57,37,26,0,0,23,56.0,53,100,90,40,98,8
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2
2,0,57,31,68,72,90,100,100,76,75,50.0,51,28,25,16,0,1
3,0,100,7,92,5,68,19,45,86,34,100.0,45,74,23,67,0,4

O código df_dsa2.loc[:3] no pandas é usado para acessar um subconjunto de linhas em um DataFrame, incluindo todas as linhas até o índice de rótulo 3. Isso significa que ele seleciona todas as linhas do início do DataFrame até e incluindo a linha que tem o rótulo de índice 3.

In [40]:
df_dsa2.loc[:3,['input1','input2','input3','input4']]

   input1  input2  input3  input4
0      47     100      27      81
1       0      89      27     100
2       0      57      31      68
3       0     100       7      92

Na linha acima retornamos todos os dados até o índice 3, mas somente algumas colunas.

In [41]:
df_dsa2.loc[:4,['input1']]

   input1
0      47
1       0
2       0
3       0
4       0

In [42]:
# Renomeando os índices
novo_index = ['linha' + str(i+1) for i in range(len(df_dsa2))]  # Cria uma lista com os novos rótulos
df_dsa2.index = novo_index  # Atribui os novos rótulos ao índice

In [43]:
df_dsa2.head()

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
linha1,47,100,27,81,57,37,26,0,0,23,56.0,53,100,90,40,98,8
linha2,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2
linha3,0,57,31,68,72,90,100,100,76,75,50.0,51,28,25,16,0,1
linha4,0,100,7,92,5,68,19,45,86,34,100.0,45,74,23,67,0,4
linha5,0,67,49,83,100,100,81,80,60,60,40.0,40,33,20,47,0,1

In [44]:
# Isso não funciona mais!!!
# df_dsa2.loc[1]

In [45]:
# Agora use isto:
df_dsa2.loc['linha2']

input1       0.0
input2      89.0
input3      27.0
input4     100.0
input5      42.0
input6      75.0
input7      29.0
input8      45.0
input9      15.0
input10     15.0
input11     37.0
input12      0.0
input13     69.0
input14      2.0
input15    100.0
input16      6.0
class        2.0
Name: linha2, dtype: float64

In [46]:
# Ou use isto:
df_dsa2.iloc[1]

input1       0.0
input2      89.0
input3      27.0
input4     100.0
input5      42.0
input6      75.0
input7      29.0
input8      45.0
input9      15.0
input10     15.0
input11     37.0
input12      0.0
input13     69.0
input14      2.0
input15    100.0
input16      6.0
class        2.0
Name: linha2, dtype: float64

## Seleção e Slicing Por Posição

In [47]:
df_dsa2.head(2)

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
linha1,47,100,27,81,57,37,26,0,0,23,56.0,53,100,90,40,98,8
linha2,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2

In [48]:
df_dsa2.iloc[1]

input1       0.0
input2      89.0
input3      27.0
input4     100.0
input5      42.0
input6      75.0
input7      29.0
input8      45.0
input9      15.0
input10     15.0
input11     37.0
input12      0.0
input13     69.0
input14      2.0
input15    100.0
input16      6.0
class        2.0
Name: linha2, dtype: float64

In [49]:
df_dsa2.iloc[[1]]

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
linha2,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2

In [50]:
# Vamos fazer o reset do índice e retornar ao formato original
df_dsa2 = df_dsa2.reset_index(drop = True)

In [51]:
df_dsa2.head(5)

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
0,47,100,27,81,57,37,26,0,0,23,56.0,53,100,90,40,98,8
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2
2,0,57,31,68,72,90,100,100,76,75,50.0,51,28,25,16,0,1
3,0,100,7,92,5,68,19,45,86,34,100.0,45,74,23,67,0,4
4,0,67,49,83,100,100,81,80,60,60,40.0,40,33,20,47,0,1

In [52]:
df_dsa2.iloc[:4,:4]

   input1  input2  input3  input4
0      47     100      27      81
1       0      89      27     100
2       0      57      31      68
3       0     100       7      92

In [53]:
# Isso aqui gera erro!!!
# df_dsa2.loc[:4,:4]

In [54]:
# ATENÇÃO!!!
df_dsa2.loc[:4,:'input4']

   input1  input2  input3  input4
0      47     100      27      81
1       0      89      27     100
2       0      57      31      68
3       0     100       7      92
4       0      67      49      83

In [55]:
df_dsa2.head(5)

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
0,47,100,27,81,57,37,26,0,0,23,56.0,53,100,90,40,98,8
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2
2,0,57,31,68,72,90,100,100,76,75,50.0,51,28,25,16,0,1
3,0,100,7,92,5,68,19,45,86,34,100.0,45,74,23,67,0,4
4,0,67,49,83,100,100,81,80,60,60,40.0,40,33,20,47,0,1

In [56]:
df_dsa2.iloc[1:4]

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2
2,0,57,31,68,72,90,100,100,76,75,50.0,51,28,25,16,0,1
3,0,100,7,92,5,68,19,45,86,34,100.0,45,74,23,67,0,4

In [57]:
df_dsa2.iloc[1:4,:]

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2
2,0,57,31,68,72,90,100,100,76,75,50.0,51,28,25,16,0,1
3,0,100,7,92,5,68,19,45,86,34,100.0,45,74,23,67,0,4

In [58]:
df_dsa2.iloc[1:4,7:10]

   input8  input9  input10
1      45      15       15
2     100      76       75
3      45      86       34

In [59]:
df_dsa2.iloc[2,3:8]

input4     68.0
input5     72.0
input6     90.0
input7    100.0
input8    100.0
Name: 2, dtype: float64

In [60]:
df_dsa2.iloc[:,3:8]

       input4  input5  input6  input7  input8
0          81      57      37      26       0
1         100      42      75      29      45
2          68      72      90     100     100
3          92       5      68      19      45
4          83     100     100      81      80
...       ...     ...     ...     ...     ...
10987      70       0      38      49      33
10988     100      52      64      32      27
10989      79       0      39      12       0
10990      61       3      23      48       0
10991      81      12      55       0      28

[10992 rows x 5 columns]

## Seleção e Slicing Por Filtro Lógico

In [61]:
df_dsa2.head()

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
0,47,100,27,81,57,37,26,0,0,23,56.0,53,100,90,40,98,8
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2
2,0,57,31,68,72,90,100,100,76,75,50.0,51,28,25,16,0,1
3,0,100,7,92,5,68,19,45,86,34,100.0,45,74,23,67,0,4
4,0,67,49,83,100,100,81,80,60,60,40.0,40,33,20,47,0,1

In [62]:
df_dsa2['input2'] < 50

0        False
1        False
2        False
3        False
4        False
         ...
10987    False
10988    False
10989    False
10990    False
10991    False
Name: input2, Length: 10992, dtype: bool

In [63]:
df_dsa2[df_dsa2['input2'] < 50]

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
7,0,39,2,62,11,5,63,0,100,43,89.0,99,36,100,0,57,0
21,0,46,49,64,78,87,100,100,91,75,85.0,49,75,24,89,0,1
34,0,0,31,15,63,30,88,52,100,79,82.0,100,56,82,79,64,9
137,0,42,30,56,59,72,86,94,100,100,80.0,68,62,35,53,0,1
146,0,42,34,57,64,79,95,100,100,85,81.0,57,62,28,45,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10805,0,43,32,58,67,79,100,100,89,76,76.0,51,63,25,59,0,1
10866,0,42,40,60,74,81,100,100,90,74,78.0,48,66,23,65,0,1
10879,0,45,42,70,66,100,60,62,47,25,1.0,5,43,0,100,4,1
10880,0,3,29,24,57,50,83,77,100,100,80.0,69,64,35,51,0,1
10933,0,15,29,40,59,68,85,97,100,100,79.0,67,60,34,46,0,1

In [64]:
df_dsa2[df_dsa2['input1'] == 0]

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2
2,0,57,31,68,72,90,100,100,76,75,50.0,51,28,25,16,0,1
3,0,100,7,92,5,68,19,45,86,34,100.0,45,74,23,67,0,4
4,0,67,49,83,100,100,81,80,60,60,40.0,40,33,20,47,0,1
6,0,100,3,72,26,35,85,35,100,71,73.0,97,65,49,66,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10969,0,66,47,97,50,100,51,60,50,20,1.0,0,35,4,100,9,1
10970,0,94,63,100,100,96,81,49,82,0,44.0,14,11,44,89,47,7
10982,0,85,21,100,66,98,83,77,90,53,100.0,30,75,10,35,0,3
10983,0,63,16,90,100,100,90,73,53,40,22.0,6,11,0,48,18,7
10984,0,74,35,100,100,96,94,63,52,35,0.0,11,5,0,77,6,2

In [65]:
df_dsa2.shape

(10992, 17)

## Mapeamento de Dados com Método Map

O método map() em Python é uma função built-in que permite aplicar uma função específica a cada item de um iterável (como uma lista ou tupla) e retorna um iterador com os resultados. Esta é uma maneira eficiente de transformar os dados sem a necessidade de usar um laço explícito.

In [66]:
seriesObj = df_dsa2['input1']

In [67]:
pandasDFseriesObj = df_dsa2[['input1']]

In [68]:
type(seriesObj)

pandas.core.series.Series

In [69]:
type(pandasDFseriesObj)

pandas.core.frame.DataFrame

In [70]:
seriesObj.dtype

dtype('int64')

In [71]:
seriesObj.map(str).dtype

dtype('O')

In [72]:
seriesObj.map(str)

0        47
1         0
2         0
3         0
4         0
         ..
10987    36
10988    16
10989    56
10990    19
10991    38
Name: input1, Length: 10992, dtype: object

In [73]:
seriesObj.map(str)[0]

'47'

In [74]:
amostra_numpy = np.array(['a','b','c','a','b','c'])

In [75]:
df_letras = pd.DataFrame(amostra_numpy, columns = ['NomeColuna'])

In [76]:
df_letras

  NomeColuna
0          a
1          b
2          c
3          a
4          b
5          c

In [77]:
dsa_dict = {'a':10, 'b':20, 'c':30}

In [78]:
df_letras['NomeColuna'].map(dsa_dict)

0    10
1    20
2    30
3    10
4    20
5    30
Name: NomeColuna, dtype: int64

In [79]:
def dsa_square_number(x):
    return x**2

In [80]:
lista_de_numeros = [1, 2, 3, 4, 5]

In [81]:
squared_numbers = map(dsa_square_number, lista_de_numeros)

In [82]:
squared_numbers_list = list(squared_numbers)

In [83]:
print(squared_numbers_list)

[1, 4, 9, 16, 25]

In [84]:
# Slicing do dataframe
df_dsa2[df_dsa2['input2'] < 50].iloc[1:5:,1:4]

     input2  input3  input4
21       46      49      64
34        0      31      15
137      42      30      56
146      42      34      57

In [85]:
# Calculamos o quadrado de cada valor no slicing
df_dsa2[df_dsa2['input2'] < 50].iloc[1:5:,1:4].map(dsa_square_number)

     input2  input3  input4
21     2116    2401    4096
34        0     961     225
137    1764     900    3136
146    1764    1156    3249

## Processamento de Dados com Método Apply

O método apply() no contexto de bibliotecas de manipulação de dados como pandas em Python é extremamente útil para aplicar uma função ao longo de um eixo de um DataFrame ou em elementos de uma Series. Ele permite uma flexibilidade significativa, sendo capaz de operar tanto em uma linha ou coluna inteira de um DataFrame, quanto em cada elemento individualmente de uma Series.

In [86]:
# Slicing do dataframe
df_dsa2[df_dsa2['input2'] < 50].iloc[1:5:,1:4]

     input2  input3  input4
21       46      49      64
34        0      31      15
137      42      30      56
146      42      34      57

In [87]:
# Aplica a função sum no eixo 0, que corresponde ao eixo das linhas. 
# Isso significa que a soma será calculada verticalmente para cada coluna no intervalo selecionado. 
# O resultado será uma série contendo a soma de cada uma dessas colunas.
df_dsa2[df_dsa2['input2'] < 50].iloc[1:5:,1:4].apply(sum, axis = 0)

input2    130
input3    144
input4    192
dtype: int64

In [88]:
# Mesmo resultado anterior
df_dsa2[df_dsa2['input2'] < 50].iloc[1:5:,1:4].apply(sum)

input2    130
input3    144
input4    192
dtype: int64

In [89]:
# Aqui, a função sum é aplicada no eixo 1, que corresponde ao eixo das colunas. 
# Isso significa que a soma será calculada horizontalmente para cada linha no intervalo de colunas selecionado. 
# O resultado será uma série contendo a soma dos valores em cada linha para as colunas selecionadas.
df_dsa2[df_dsa2['input2'] < 50].iloc[1:5:,1:4].apply(sum, axis = 1)

21     159
34      46
137    128
146    133
dtype: int64

### Método Apply com Expressão Lambda

Expressão Lambda é função anônima em Python (existe somente em tempo de execução).

As expressões lambda em Python são uma maneira concisa de declarar funções anônimas, ou seja, funções sem um nome definido. Elas são particularmente úteis quando você precisa de uma função simples por um curto período de tempo e não quer a formalidade de definir uma função com def. As expressões lambda são muitas vezes usadas em conjunto com funções de ordem superior, como map(), filter() e reduce(), bem como métodos como apply() em pandas.

In [90]:
# Criando um DataFrame com duas colunas de números
df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60]
})

In [91]:
# Aplicando a função lambda para dobrar cada valor
doubled_df = df.apply(lambda x: x * 2)

In [92]:
print(doubled_df)

    A    B
0  20   80
1  40  100
2  60  120

In [93]:
# Cria uma função
def dsa_converte_dados(x):
    if x < 10:
        return 'G10'
    elif x < 50:
        return 'G50'
    elif x < 90:
        return 'G90'
    else:
        return 'NO'

In [94]:
df_dsa2['input4']

0         81
1        100
2         68
3         92
4         83
        ...
10987     70
10988    100
10989     79
10990     61
10991     81
Name: input4, Length: 10992, dtype: int64

In [95]:
df_dsa2['input4'].apply(lambda x: dsa_converte_dados(x))

0        G90
1         NO
2        G90
3         NO
4        G90
        ...
10987    G90
10988     NO
10989    G90
10990    G90
10991    G90
Name: input4, Length: 10992, dtype: object

In [96]:
df_dsa2['input4'].apply(dsa_converte_dados)

0        G90
1         NO
2        G90
3         NO
4        G90
        ...
10987    G90
10988     NO
10989    G90
10990    G90
10991    G90
Name: input4, Length: 10992, dtype: object

In [97]:
df_dsa2['input4'].map(dsa_converte_dados)

0        G90
1         NO
2        G90
3         NO
4        G90
        ...
10987    G90
10988     NO
10989    G90
10990    G90
10991    G90
Name: input4, Length: 10992, dtype: object

In [98]:
# Tempo de execução
a = datetime.datetime.now()
df_dsa2['input4'].apply(lambda x: dsa_converte_dados(x))
b = datetime.datetime.now()
print (b-a)

0:00:00.000924

In [99]:
# Tempo de execução
a = datetime.datetime.now()
df_dsa2['input4'].apply(dsa_converte_dados)
b = datetime.datetime.now()
print (b-a)

0:00:00.001006

In [100]:
# Tempo de execução
a = datetime.datetime.now()
df_dsa2['input4'].map(dsa_converte_dados)
b = datetime.datetime.now()
print (b-a)

0:00:00.000939

Para a maioria dos casos onde a função aplicada é simples e direta, map() é uma escolha melhor em termos de velocidade.

In [101]:
df_dsa2.map(dsa_converte_dados).head()

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
0,G50,NO,G50,G90,G90,G50,G50,G10,G10,G50,G90,G90,NO,NO,G50,NO,G10
1,G10,G90,G50,NO,G50,G90,G50,G50,G50,G50,G50,G10,G90,G10,NO,G10,G10
2,G10,G90,G50,G90,G90,NO,NO,NO,G90,G90,G90,G90,G50,G50,G50,G10,G10
3,G10,NO,G10,NO,G10,G90,G50,G50,G90,G50,NO,G50,G90,G50,G90,G10,G10
4,G10,G90,G50,G90,NO,NO,G90,G90,G90,G90,G50,G50,G50,G50,G50,G10,G10

In [102]:
# Cria uma função
def dsa_divide(x,y):
    try:
        return (x/y)
    except:
        return 0

In [103]:
df_dsa2.head()

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12,input13,input14,input15,input16,class
0,47,100,27,81,57,37,26,0,0,23,56.0,53,100,90,40,98,8
1,0,89,27,100,42,75,29,45,15,15,37.0,0,69,2,100,6,2
2,0,57,31,68,72,90,100,100,76,75,50.0,51,28,25,16,0,1
3,0,100,7,92,5,68,19,45,86,34,100.0,45,74,23,67,0,4
4,0,67,49,83,100,100,81,80,60,60,40.0,40,33,20,47,0,1

In [104]:
df_dsa2[['input3','input4']].apply(lambda x: dsa_divide(*x), axis = 1)

0        0.333333
1        0.270000
2        0.455882
3        0.076087
4        0.590361
           ...
10987    0.342857
10988    0.410000
10989    0.341772
10990    0.000000
10991    0.456790
Length: 10992, dtype: float64

## Dicing de Dataframes

Para exemplificar o "dicing" com pandas, vamos criar um pequeno DataFrame e então selecionar dados específicos dele, combinando condições em múltiplas colunas. "Dicing" é um termo usado para descrever a seleção de uma subseção específica de um conjunto de dados, baseando-se em critérios específicos, similar ao que faríamos ao cortar um dado (ou "dice") em partes menores.

Primeiro, criaremos um DataFrame pandas com dados fictícios:

In [105]:
# Criando um DataFrame de exemplo
dados_dsa = {
    'Nome': ['Ana', 'Bruno', 'Carla', 'Diego', 'Eva', 'Fábio'],
    'Idade': [23, 34, 45, 26, 29, 35],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'São Paulo', 'Curitiba', 'Rio de Janeiro', 'Curitiba']
}

In [106]:
# Converte o dicionário em dataframe
df = pd.DataFrame(dados_dsa)

In [107]:
# Mostra o DataFrame criado
print(df)

    Nome  Idade          Cidade
0    Ana     23       São Paulo
1  Bruno     34  Rio de Janeiro
2  Carla     45       São Paulo
3  Diego     26        Curitiba
4    Eva     29  Rio de Janeiro
5  Fábio     35        Curitiba

In [108]:
# Selecionando pessoas com mais de 30 anos que vivem no Rio de Janeiro
filtro = (df['Idade'] > 30) & (df['Cidade'] == 'Rio de Janeiro')

In [109]:
df_filtrado = df[filtro]

In [110]:
# Mostrando o resultado do dicing
print(df_filtrado)

    Nome  Idade          Cidade
1  Bruno     34  Rio de Janeiro

## Merge, Join e Concatenação

In [111]:
# DataFrames de exemplo para Merge e Join

df_a = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'Nome': ['Ana', 'Bruno', 'Carla', 'Diego']
})

df_b = pd.DataFrame({
    'id': [2, 3, 4, 5],
    'Idade': [34, 45, 26, 29]
})

# DataFrame adicional para Concatenação
df_c = pd.DataFrame({
    'id': [6, 7],
    'Nome': ['Eva', 'Fábio'],
    'Idade': [32, 28]
})

In [112]:
# Merge (Inner Join) baseado na coluna 'id'
df_merged = pd.merge(df_a, df_b, on = 'id')

In [113]:
print("Merge (Inner Join):\n", df_merged)

Merge (Inner Join):
    id   Nome  Idade
0   2  Bruno     34
1   3  Carla     45
2   4  Diego     26

In [114]:
# Definindo 'id' como índice para usar no Join
df_a_indexed = df_a.set_index('id')
df_b_indexed = df_b.set_index('id')

In [115]:
# Join dos DataFrames no índice
df_joined = df_a_indexed.join(df_b_indexed, how = 'inner')

In [116]:
print("Join baseado em índice:\n", df_joined)

Join baseado em índice:
      Nome  Idade
id
2   Bruno     34
3   Carla     45
4   Diego     26

In [117]:
# Join dos DataFrames no índice
df_joined = df_a_indexed.join(df_b_indexed, how = 'outer')

In [118]:
print("Join baseado em índice:\n", df_joined)

Join baseado em índice:
      Nome  Idade
id
1     Ana    NaN
2   Bruno   34.0
3   Carla   45.0
4   Diego   26.0
5     NaN   29.0

In [119]:
# Concatenação vertical (adicionando linhas)
df_concat_v = pd.concat([df_a, df_c], ignore_index = True)

In [120]:
print("Concatenação Vertical:\n", df_concat_v)

Concatenação Vertical:
    id   Nome  Idade
0   1    Ana    NaN
1   2  Bruno    NaN
2   3  Carla    NaN
3   4  Diego    NaN
4   6    Eva   32.0
5   7  Fábio   28.0

> Para concatenação horizontal, assegure-se de que os DataFrames compartilham o mesmo índice ou redefina-os conforme necessário.

In [121]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

In [122]:
#%watermark -v -m

In [123]:
#%watermark --iversions

# Fim