<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
## <font color='blue'>Automação de Processos e Engenharia de Dados com Python, Excel e IA</font>
## <font color='blue'>Exercícios</font>

## Pacotes Python Usados no Projeto

In [4]:
# Instala o pacote watermark
%pip install -q -U watermark

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
# Imports
import pandas as pd

In [6]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

Neste exercício você vai praticar suas habilidades de pesquisa e estudar a função pivot.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html

Então considere o dataframe abaixo e crie o código Python que gera as 5 tabelas pivot a seguir. Compare suas respostas com o gabarito fornecido.

In [7]:
# Dataframe
df = pd.DataFrame({
    'Montadora': ['Porsche', 'Honda', 'Toyota', 'BMW', 'Porsche', 'Honda', 'Toyota', 'BMW'],
    'Localidade': ['EUA', 'EUA', 'EUA', 'EUA', 'Alemanha', 'Alemanha', 'Alemanha', 'Alemanha'],
    'Modelo':['Taycan', 'Civic', 'Corolla', 'Z4', 'Macan', 'Accord', 'Camry', 'X3'],
    'Unidades_Vendidas': [97, 75, 84, 92, 120, 98, 76, 81]})

In [ ]:
df

  Montadora Localidade   Modelo  Unidades_Vendidas
0   Porsche        EUA   Taycan                 97
1     Honda        EUA    Civic                 75
2    Toyota        EUA  Corolla                 84
3       BMW        EUA       Z4                 92
4   Porsche   Alemanha    Macan                120
5     Honda   Alemanha   Accord                 98
6    Toyota   Alemanha    Camry                 76
7       BMW   Alemanha       X3                 81

In [16]:
# Tabela Pivot 1
pivot1 = df.pivot_table(index='Montadora', values='Unidades_Vendidas', aggfunc='sum')
pivot1

           Unidades_Vendidas
Montadora
BMW                      173
Honda                    173
Porsche                  217
Toyota                   160

In [17]:
# Tabela Pivot 2
pivot2 = df.pivot_table(index='Localidade', values='Unidades_Vendidas', aggfunc='sum')
pivot2

            Unidades_Vendidas
Localidade
Alemanha                  375
EUA                       348

In [18]:
# Tabela Pivot 3
pivot3 = df.pivot_table(index='Localidade', columns='Montadora', values='Unidades_Vendidas', aggfunc='sum')
pivot3

Montadora   BMW  Honda  Porsche  Toyota
Localidade
Alemanha     81     98      120      76
EUA          92     75       97      84

In [19]:
# Tabela Pivot 4
pivot4 = df.pivot_table(index='Montadora', values='Unidades_Vendidas', aggfunc='mean')
pivot4

           Unidades_Vendidas
Montadora
BMW                     86.5
Honda                   86.5
Porsche                108.5
Toyota                  80.0

In [20]:
# Tabela Pivot 5
pivot5 = df.pivot_table(index='Localidade', values='Unidades_Vendidas', aggfunc='mean')
pivot5

            Unidades_Vendidas
Localidade
Alemanha                93.75
EUA                     87.00

In [13]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

In [14]:
#%watermark

In [15]:
#%watermark --iversions

# Fim