In [5]:
%pip install -q -U watermark
import xlrd
import numpy as np
import pandas as pd
%reload_ext watermark
%watermark -a "Data Science Academy"
df_dsa = pd.read_excel('dataset.xls')

Note: you may need to restart the kernel to use updated packages.
Author: Data Science Academy

## Pipeline 1 - Estatísticas de Vendas com Pivot Table

Objetivo: Criar uma tabela com a média e desvio padrão de vendas e lucro por subcategoria. A tabela deve conter para cada registro a diferença entre a média e o desvio padrão.

Média é um valor que tenta resumir um conjunto de dados representando o "centro" desses dados. É calculada somando todos os valores do conjunto e dividindo o total pelo número de valores. A média dá uma boa ideia do que é típico ou comum para aquele conjunto de dados.

Desvio padrão é uma medida que indica a quantidade de variação ou dispersão dos dados em relação à média. Um desvio padrão baixo significa que os dados estão agrupados muito próximos da média, indicando pouca variação. Um desvio padrão alto indica que os dados estão mais espalhados, mostrando uma maior variação em relação à média.

In [9]:
# Criando a Pivot Table para calcular a média de Sales e Profit por Sub-Category
df_dsa_media_info = pd.pivot_table(df_dsa, 
                                   index = 'Sub-Category',  # ← CORRIGIDO: hífen
                                   values = ['Sales', 'Profit'], 
                                   aggfunc = 'mean').reset_index()

# Renomeando as colunas para facilitar o acesso futuro
df_dsa_media_info.columns = ['Sub_Category', 'Mean_Profit', 'Mean_Sales']

# Visualizando as primeiras linhas do resultado
df_dsa_media_info.head()

  Sub_Category  Mean_Profit  Mean_Sales
0  Accessories    54.111788  215.974604
1   Appliances    38.922758  230.755710
2          Art     8.200737   34.068834
3      Binders    19.843574  133.560560
4    Bookcases   -15.230509  503.859633

In [10]:
# Criando a Pivot Table para calcular o Desvio Padrão (std) de Sales e Profit
df_dsa_desvio_info = pd.pivot_table(df_dsa, 
                                    index = 'Sub-Category',  # ← CORRIGIDO: hífen
                                    values = ['Sales', 'Profit'], 
                                    aggfunc = 'std').reset_index()

# Ajustando os nomes das colunas para snake_case
df_dsa_desvio_info.columns = ['Sub_Category', 'STD_Profit', 'STD_Sales']

# Visualizando as primeiras linhas do resultado
df_dsa_desvio_info.head()

  Sub_Category  STD_Profit   STD_Sales
0  Accessories  106.155455  334.965015
1   Appliances  148.319146  388.949643
2          Art   13.384264   60.122465
3      Binders  306.196773  563.251188
4    Bookcases  182.034224  638.748523

In [11]:
# Unindo os DataFrames de Média e Desvio Padrão
df_pipe_1 = pd.merge(df_dsa_media_info, 
                     df_dsa_desvio_info, 
                     on = 'Sub_Category', 
                     how = 'left')

# Visualizando o resultado
df_pipe_1.head()

  Sub_Category  Mean_Profit  Mean_Sales  STD_Profit   STD_Sales
0  Accessories    54.111788  215.974604  106.155455  334.965015
1   Appliances    38.922758  230.755710  148.319146  388.949643
2          Art     8.200737   34.068834   13.384264   60.122465
3      Binders    19.843574  133.560560  306.196773  563.251188
4    Bookcases   -15.230509  503.859633  182.034224  638.748523

In [12]:
# Calcula a diferença da média de lucro em relação ao desvio
df_pipe_1['diffMean'] = df_pipe_1['Mean_Profit'] - df_pipe_1['STD_Profit']

# Calcula a diferença da média de vendas em relação ao desvio
df_pipe_1['diffSTD'] = df_pipe_1['Mean_Sales'] - df_pipe_1['STD_Sales']

# Ordena a tabela
df_pipe_1.sort_values(by = ['diffMean'], ascending = False)

,Sub_Category,Mean_Profit,Mean_Sales,STD_Profit,STD_Sales,diffMean,diffSTD
8,Fasteners,4.375660,13.936774,5.055053,12.416593,-0.679393,1.520181
2,Art,8.200737,34.068834,13.384264,60.122465,-5.183527,-26.053631
7,Envelopes,27.418019,64.867724,35.354983,84.351633,-7.936964,-19.483908
12,Paper,24.856620,57.284092,35.225214,78.167639,-10.368594,-20.883547
10,Labels,15.236962,34.303055,34.084127,74.119287,-18.847165,-39.816232
9,Furnishings,13.645918,95.825668,52.753228,147.893640,-39.107310,-52.067972
0,Accessories,54.111788,215.974604,106.155455,334.965015,-52.043667,-118.990411
14,Storage,25.152277,264.590553,81.923600,355.222507,-56.771323,-90.631953
13,Phones,50.073938,371.211534,113.251277,491.457343,-63.177339,-120.245808
5,Chairs,43.095894,532.332420,127.099922,550.148243,-84.004028,-17.815823
1,Appliances,38.922758,230.755710,148.319146,388.949643,-109.396388,-158.193933
15,Supplies,-6.258418,245.650200,105.059628,923.828753,-111.318047,-678.178553
4,Bookcases,-15.230509,503.859633,182.034224,638.748523,-197.264733,-134.888890
16,Tables,-55.565771,648.794771,230.565006,615.774655,-286.130778,33.020116
3,Binders,19.843574,133.560560,306.196773,563.251188,-286.353199,-429.690627
6,Copiers,817.909190,2198.941618,1460.921156,3175.665867,-643.011967,-976.724250
11,Machines,29.432669,1645.553313,1099.070067,2765.102088,-1069.637398,-1119.548775

In [13]:
type(df_pipe_1)

pandas.core.frame.DataFrame